### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SmileGamez** [Martomate/Hexacraft#41]
The game crashes when using `sbt run`. I am using Windows and Java 11. Please consider fixing it!

```
java.lang.NullPointerException
        at com.martomate.hexacraft.world.render.ChunkRendererImpl.$anonfun$updateContent$3(ChunkRendererImpl.scala:51)
        at com.martomate.hexacraft.world.render.ChunkRendererImpl.$anonfun$updateContent$3$adapted(ChunkRendererImpl.scala:48)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791)
        at com.martomate.hexacraft.world.render.ChunkRendererImpl.$anonfun$updateContent$1(ChunkRendererImpl.scala:48)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.martomate.hexacraft.world.render.ChunkRendererImpl.updateContent(ChunkRendererImpl.scala:42)
        at com.martomate.hexacraft.world.render.ChunkRenderHandler.updateChunk(ChunkRenderHandler.scala:25)
        at com.martomate.hexacraft.world.render.selector.ChunkRenderSelectorIdentity.updateChunk(ChunkRenderSelector.scala:19)
        at com.martomate.hexacraft.world.render.WorldRenderer.$anonfun$chunkRenderUpdater$2(WorldRenderer.scala:59)
        at com.martomate.hexacraft.world.render.WorldRenderer.$anonfun$chunkRenderUpdater$2$adapted(WorldRenderer.scala:59)
        at scala.Option.foreach(Option.scala:274)
        at com.martomate.hexacraft.world.render.WorldRenderer.$anonfun$chunkRenderUpdater$1(WorldRenderer.scala:59)
        at com.martomate.hexacraft.world.render.WorldRenderer.$anonfun$chunkRenderUpdater$1$adapted(WorldRenderer.scala:57)
        at com.martomate.hexacraft.world.render.ChunkRenderUpdater.$anonfun$update$1(ChunkRenderUpdater.scala:28)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.martomate.hexacraft.world.render.ChunkRenderUpdater.update(ChunkRenderUpdater.scala:26)
        at com.martomate.hexacraft.world.render.WorldRenderer.tick(WorldRenderer.scala:64)
        at com.martomate.hexacraft.game.GameScene.tick(GameScene.scala:230)
        at com.martomate.hexacraft.main.MainWindow.$anonfun$tick$1(MainWindow.scala:149)
        at com.martomate.hexacraft.main.MainWindow.$anonfun$tick$1$adapted(MainWindow.scala:149)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at com.martomate.hexacraft.main.SceneStackImpl.foreach(SceneStackImpl.scala:7)
        at com.martomate.hexacraft.main.MainWindow.tick(MainWindow.scala:149)
        at com.martomate.hexacraft.main.MainWindow.$anonfun$loop$1(MainWindow.scala:71)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.martomate.hexacraft.main.MainWindow.loop(MainWindow.scala:70)
        at com.martomate.hexacraft.main.MainWindow.run(MainWindow.scala:163)
        at com.martomate.hexacraft.main.Main$.main(Main.scala:13)
        at com.martomate.hexacraft.main.Main.main(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.Run.invokeMain(Run.scala:98)
        at sbt.Run.run0(Run.scala:92)
        at sbt.Run.execute$1(Run.scala:68)
        at sbt.Run.$anonfun$run$4(Run.scala:80)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
        at sbt.TrapExit$App.run(TrapExit.scala:253)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
/SmileGamez

**Comment by Martomate** [comment]
This was likely fixed in April of 2020 in c9f0f2084583fa891754cd8ecfd4d3f062eb1747. The problem was the following:

- `ChunkRenderImpl.updateContent` called `ChunkCache.neighbor`
- `ChunkCache.neighbor` returned `null` (there was no chunk) but it should have returned `None`
- The chunk renderer wasn't expecting a `null` value, resulting in a `NullPointerException`

This behaviour was fixed In April of 2020 and the change can be seen [here](https://github.com/Martomate/Hexacraft/commit/c9f0f2084583fa891754cd8ecfd4d3f062eb1747#diff-2309753fcffe1efea52f089b68764bb584ad15309f6027841cbd8cece1ea1e27).

I will close this issue since the bug is likely fixed. If you find any problems in the future, feel free to create a new issue!

Have a nice day!
